/* Good King V0.9.6 — Service Worker con instalación atómica */
const CACHE_NAME='good-king-v096-shell',CACHE_PREFIX='good-king-',IMAGE_CACHE_NAME='good-king-v096-product-images';
const PRODUCT_IMAGE_HOSTS=new Set(['www.coca-cola.com','images.pexels.com','www.jugosbolivianos.com.bo']);
const LOCAL_SHELL=['./','./index.html','./styles.css?v=0.9.4','./v094.css?v=0.9.4','./v095.css?v=0.9.6','./config.js?v=0.9.4','./vendor/supabase-lite.js?v=0.9.4','./app.js?v=0.9.4','./v06.js?v=0.9.4','./v07.js?v=0.9.4','./v08.js?v=0.9.4','./v09.js?v=0.9.4','./v092.js?v=0.9.4','./v093.js?v=0.9.4','./v094.js?v=0.9.4','./v095.js?v=0.9.6','./manifest.webmanifest?v=0.9.6','./version.json','./assets/logo.jpg','./assets/icon-192.png','./assets/icon-512.png','./assets/icon-maskable-512.png','./assets/apple-touch-icon.png','./assets/favicon-64.png'];
async function installAtomically(){await caches.delete(CACHE_NAME);const c=await caches.open(CACHE_NAME);try{for(const u of LOCAL_SHELL){const q=new Request(u,{cache:'reload'}),r=await fetch(q);if(!r?.ok)throw new Error(`Recurso obligatorio no disponible: ${u}`);await c.put(q,r.clone())}await c.put(new Request('./__shell_complete__'),new Response('0.9.6'))}catch(e){await caches.delete(CACHE_NAME);throw e}}
self.addEventListener('install',e=>e.waitUntil(installAtomically()));self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});self.addEventListener('activate',e=>e.waitUntil((async()=>{const c=await caches.open(CACHE_NAME);if(!await c.match('./__shell_complete__'))throw new Error('App Shell V0.9.6 incompleto');const ks=await caches.keys();await Promise.all(ks.filter(k=>k.startsWith(CACHE_PREFIX)&&![CACHE_NAME,IMAGE_CACHE_NAME].includes(k)).map(k=>caches.delete(k)));await self.clients.claim()})()));
async function networkFirst(q,f='./index.html'){const c=await caches.open(CACHE_NAME);try{const r=await fetch(q,{cache:'no-store'});if(r?.ok)await c.put(q,r.clone());return r}catch(e){return(await c.match(q,{ignoreSearch:true}))||(f?await c.match(f,{ignoreSearch:true}):null)||Response.error()}}
async function cacheFirst(q){const c=await caches.open(CACHE_NAME),x=await c.match(q,{ignoreSearch:true});if(x)return x;try{const r=await fetch(q);if(r?.ok)await c.put(q,r.clone());return r}catch(e){return Response.error()}}
async function productImageCache(q){const c=await caches.open(IMAGE_CACHE_NAME),x=await c.match(q);const n=fetch(q).then(async r=>{if(r&&(r.ok||r.type==='opaque'))await c.put(q,r.clone());return r}).catch(()=>null);return x||await n||Response.error()}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==self.location.origin){if(e.request.destination==='image'&&PRODUCT_IMAGE_HOSTS.has(u.hostname))e.respondWith(productImageCache(e.request));return}if(e.request.mode==='navigate')return e.respondWith(networkFirst(e.request));if(/\/(version\.json|config\.js)$/.test(u.pathname))return e.respondWith(networkFirst(e.request,null));e.respondWith(cacheFirst(e.request))});