
'use strict';

let pendingProductImageFile = null;
let removeExistingProductImage = false;
const originalRenderModuleV05 = renderModule;
const originalPushQueueItemV05 = pushQueueItem;
const originalPullRemoteCoreDataV05 = pullRemoteCoreData;

function inventoryNumber(value) {
  return new Intl.NumberFormat('es-BO',{maximumFractionDigits:2}).format(Number(value||0));
}

function productVisualHTML(product, admin=false) {
  if (product.imageUrl) return `<img class="${admin?'admin-product-photo':'product-photo'}" src="${escapeHTML(product.imageUrl)}" alt="${escapeHTML(product.name)}" loading="lazy" />`;
  return `<span class="food-emoji">${escapeHTML(product.emoji || '🍽️')}</span>`;
}

renderProducts = function() {
  const query = $('searchInput').value.trim().toLowerCase();
  const list = products.filter(product => product.active !== false && product.category === currentCategory && (!query || product.name.toLowerCase().includes(query)));
  $('productGrid').innerHTML = list.map(product => {
    const quantity = getCartQuantity(product.id);
    const soldOut = product.status === 'soldout';
    const low = product.status === 'low';
    return `<article class="product-card ${soldOut ? 'soldout' : ''} ${low ? 'low-stock' : ''}">
      <div class="product-visual"><span class="product-badge">${escapeHTML(soldOut ? 'Agotado' : low ? 'Poco stock' : product.badge)}</span>${productVisualHTML(product)}</div>
      <div class="product-body"><h3>${escapeHTML(product.name)}</h3><p>${escapeHTML(product.desc || '')}</p><div class="product-price"><strong>${money(product.price)}</strong><small>${soldOut ? 'No disponible temporalmente' : 'Precio unitario'}</small></div><div class="product-stepper"><button data-id="${escapeHTML(product.id)}" data-delta="-1" ${quantity===0?'disabled':''}>−</button><b>${quantity}</b><button data-id="${escapeHTML(product.id)}" data-delta="1" ${soldOut?'disabled':''}>＋</button></div></div>
    </article>`;
  }).join('') || '<div class="empty-state">No se encontraron productos.</div>';
  $('productGrid').querySelectorAll('.product-stepper button').forEach(button => button.onclick=()=>changeProductQuantity(button.dataset.id,Number(button.dataset.delta)));
};

renderProductsAdminModule = async function() {
  const rows = products.map(product => `<article class="admin-product-row ${product.active === false ? 'inactive' : ''}"><div class="admin-product-icon">${productVisualHTML(product,true)}</div><div><b>${escapeHTML(product.name)}</b><small>${escapeHTML(product.category)} · ${product.status==='soldout'?'Agotado':product.status==='low'?'Poco stock':'Disponible'}${product.active===false?' · Oculto':''}</small></div><strong>${money(product.price)}</strong><button class="button-light edit-product" data-id="${product.id}">Editar</button></article>`).join('');
  return `<div class="module-summary"><div><small>Productos configurados</small><strong>${products.length}</strong></div><div><small>Con fotografía</small><strong>${products.filter(p=>p.imageUrl).length}</strong></div><button id="newProductBtn" class="primary-action">＋ Nuevo producto</button></div><div class="admin-products-list">${rows}</div>`;
};

function updateProductImagePreview(product=null) {
  const box=$('productImagePreview');
  if (!box) return;
  if (pendingProductImageFile) { const url=URL.createObjectURL(pendingProductImageFile); box.innerHTML=`<img src="${url}" alt="Vista previa" />`; return; }
  if (product?.imageUrl && !removeExistingProductImage) box.innerHTML=`<img src="${escapeHTML(product.imageUrl)}" alt="${escapeHTML(product.name||'Producto')}" />`;
  else box.innerHTML='<span>Sin fotografía</span>';
}

openProductDialog = function(product=null) {
  $('productDialogTitle').textContent=product?'Editar producto':'Nuevo producto'; $('productId').value=product?.id||''; $('productName').value=product?.name||''; $('productPrice').value=Number(product?.price||0); $('productCategory').value=product?.category||'Menú'; $('productDesc').value=product?.desc||''; $('productBadge').value=product?.badge||''; $('productEmoji').value=product?.emoji||'🍽️'; $('productStatus').value=product?.status||'available'; $('productActive').checked=product?.active!==false; pendingProductImageFile=null; removeExistingProductImage=false; $('productImageFile').value=''; updateProductImagePreview(product); $('productDialog').showModal();
};

async function uploadProductImage(file, productId) {
  if (!file) return null;
  if (!supabaseClient || !authContext || authContext.offline || !navigator.onLine) throw new Error('Conéctate a internet para subir la fotografía.');
  if (file.size > 5*1024*1024) throw new Error('La fotografía supera 5 MB.');
  const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');
  const path=`${authContext.businessId}/${productId}.${ext}`;
  const {error}=await supabaseClient.storage.from('product-images').upload(path,file,{upsert:true,contentType:file.type||'image/jpeg',cacheControl:'3600'});
  if (error) throw error;
  const {data}=supabaseClient.storage.from('product-images').getPublicUrl(path);
  return {imageUrl:data.publicUrl,imagePath:path};
}

saveProduct = async function(event) {
  event.preventDefault(); if(!canManageBusiness()) return toast('Solo la propietaria o el administrador pueden modificar productos.');
  const name=$('productName').value.trim(); if(!name)return toast('Ingresa el nombre del producto.');
  const requestedId=$('productId').value; const id=requestedId||`${slugifyProduct(name)}-${Date.now().toString(36)}`; const existing=await getRecord('productCatalog',id); const maxOrder=Math.max(0,...products.map(i=>Number(i.sortOrder||0)));
  let imageData={imageUrl:removeExistingProductImage?'':existing?.imageUrl||'',imagePath:removeExistingProductImage?'':existing?.imagePath||''};
  try { if(pendingProductImageFile) imageData=await uploadProductImage(pendingProductImageFile,id); } catch(error){ return toast(error.message||'No se pudo subir la fotografía.',4800); }
  const product={...(existing||{}),id,name,price:Number($('productPrice').value||0),category:$('productCategory').value,desc:$('productDesc').value.trim(),badge:$('productBadge').value.trim()||'Good King',emoji:$('productEmoji').value.trim()||'🍽️',status:$('productStatus').value,active:$('productActive').checked,sortOrder:existing?.sortOrder||maxOrder+1,...imageData,createdAt:existing?.createdAt||nowIso(),updatedAt:nowIso(),appVersion:APP_VERSION};
  const tx=db.transaction(['productCatalog','syncQueue','auditLogs'],'readwrite'); tx.objectStore('productCatalog').put(product); tx.objectStore('syncQueue').put(queueRecord('productCatalog',product)); tx.objectStore('auditLogs').put({id:uid(),action:existing?'product_updated':'product_created',entity:'productCatalog',entityId:id,details:{name,price:product.price,status:product.status,image:Boolean(product.imageUrl)},createdAt:nowIso(),appVersion:APP_VERSION}); await transactionPromise(tx); await ensureDefaultCatalog(); $('productDialog').close(); renderProducts(); await renderModule('products'); await refreshStatus(); scheduleAutoBackup('actualización de productos'); toast('Producto y fotografía guardados.');
};

async function loadInventoryLocal() {
  return (await getAllRecords('inventoryIngredients')).filter(x=>x.active!==false).sort((a,b)=>a.name.localeCompare(b.name,'es'));
}

async function renderInventoryModule() {
  const rows=await loadInventoryLocal();
  const low=rows.filter(x=>Number(x.theoreticalQuantity||0)<=Number(x.minimumStock||0));
  const cards=rows.map(x=>{const q=Number(x.theoreticalQuantity||0), min=Number(x.minimumStock||0), isLow=q<=min; return `<article class="inventory-row ${isLow?'low':''}"><div class="inventory-icon">${isLow?'⚠️':'▦'}</div><div><b>${escapeHTML(x.name)}</b><small>Compra: ${escapeHTML(x.purchaseUnit||x.baseUnit)} · conversión ${inventoryNumber(x.conversionFactor||1)} ${escapeHTML(x.baseUnit)}</small><small>Costo promedio: ${money(Number(x.averageCost||0))} por ${escapeHTML(x.baseUnit)}</small></div><div class="inventory-stock"><strong>${inventoryNumber(q)} ${escapeHTML(x.baseUnit)}</strong><small>Mínimo ${inventoryNumber(min)}</small></div><div class="inventory-actions"><button class="button-light edit-ingredient" data-id="${x.id}">Editar</button><button class="secondary-action adjust-inventory" data-id="${x.id}">Ajustar</button></div></article>`}).join('');
  const movements=(await getAllRecords('inventoryMovementsLocal')).sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,12);
  const ingredientMap=Object.fromEntries(rows.map(x=>[x.id,x]));
  const movementLabels={purchase:'Compra',sale:'Venta',sale_reversal:'Reposición por anulación',count:'Conteo físico',entry:'Ingreso manual',waste:'Merma',adjustment_in:'Ajuste de entrada',adjustment_out:'Ajuste de salida'};
  const history=movements.map(m=>{const item=ingredientMap[m.ingredientId]||{};const qty=Number(m.quantity||0);const direction=qty>=0?'positive':'negative';return `<article class="inventory-history-row"><span class="movement-sign ${direction}">${qty>=0?'＋':'−'}</span><div><b>${escapeHTML(item.name||m.ingredientName||'Insumo')}</b><small>${escapeHTML(movementLabels[m.type]||m.type||'Movimiento')} · ${new Date(m.createdAt).toLocaleString('es-BO')}</small><small>${escapeHTML(m.detail||'Sin detalle')}</small></div><div><strong class="${direction}">${qty>=0?'+':''}${inventoryNumber(qty)} ${escapeHTML(item.baseUnit||m.baseUnit||'')}</strong><small>${inventoryNumber(m.beforeQuantity||0)} → ${inventoryNumber(m.afterQuantity||0)}</small></div></article>`}).join('');
  return `<div class="module-summary"><div><small>Insumos activos</small><strong>${rows.length}</strong></div><div><small>Stock bajo</small><strong>${low.length}</strong></div><div><small>Valor estimado</small><strong>${money(rows.reduce((s,x)=>s+Number(x.theoreticalQuantity||0)*Number(x.averageCost||0),0))}</strong></div><button id="newIngredientBtn" class="primary-action">＋ Nuevo insumo</button></div><div class="inventory-toolbar"><button id="quickPurchaseBtn" class="secondary-action">🛍 Registrar compra</button><button id="seedIngredientsBtn" class="button-light">Cargar insumos iniciales</button></div><div class="inventory-list">${cards||'<div class="empty-state">Todavía no hay insumos. Carga la base inicial o crea el primero.</div>'}</div><section class="module-subsection"><div class="subsection-title"><div><p class="eyebrow">Trazabilidad</p><h2>Movimientos recientes</h2></div><small>Entradas, consumos, mermas y ajustes quedan registrados.</small></div><div class="inventory-history">${history||'<div class="empty-state compact">Todavía no existen movimientos de inventario.</div>'}</div></section>`;
}

async function renderPurchasesModule() {
  const allPurchases=(await getAllRecords('purchasesLocal')).sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')));
  const purchases=allPurchases.slice(0,100);
  const previousByIngredient={};
  const comparisons={};
  [...allPurchases].reverse().forEach(p=>{const key=p.ingredientId||p.ingredientName||p.description;const previous=previousByIngredient[key];if(previous){const currentUnit=Number(p.convertedQuantity||0)>0?Number(p.total||0)/Number(p.convertedQuantity):0;const previousUnit=Number(previous.convertedQuantity||0)>0?Number(previous.total||0)/Number(previous.convertedQuantity):0;comparisons[p.id]={previous,delta:currentUnit-previousUnit,currentUnit,previousUnit,days:Math.max(0,Math.round((new Date(p.createdAt)-new Date(previous.createdAt))/86400000))};}previousByIngredient[key]=p;});
  const paymentLabel={cash:'Caja',cash_register:'Caja',external:'Dinero externo',credit:'Crédito'};
  const list=purchases.map(p=>{const c=comparisons[p.id];const deltaClass=!c?'':c.delta>0?'negative':c.delta<0?'positive':'';const deltaText=!c?'Primera referencia':`${c.delta>0?'Subió':c.delta<0?'Bajó':'Sin cambio'} ${money(Math.abs(c.delta))} por ${escapeHTML(p.baseUnit||'unidad')} · ${c.days} día(s) desde la anterior`;return `<article class="purchase-row enriched"><div class="purchase-main"><b>${escapeHTML(p.ingredientName||p.description||'Compra')}</b><small>${new Date(p.createdAt).toLocaleString('es-BO')} · ${escapeHTML(p.supplier||'Sin proveedor')}</small><span class="purchase-source">${escapeHTML(paymentLabel[p.paymentSource]||p.paymentSource||'Dinero externo')}</span></div><div class="purchase-quantity"><strong>${inventoryNumber(p.quantity||0)} ${escapeHTML(p.purchaseUnit||'')}</strong><small>Ingresó ${inventoryNumber(p.convertedQuantity)} ${escapeHTML(p.baseUnit||'')}</small></div><div class="purchase-price"><strong>${money(p.total)}</strong><small>${Number(p.convertedQuantity||0)>0?`${money(Number(p.total||0)/Number(p.convertedQuantity))} / ${escapeHTML(p.baseUnit||'unidad')}`:'Sin costo unitario'}</small><small class="${deltaClass}">${deltaText}</small></div></article>`}).join('');
  const total=allPurchases.reduce((s,p)=>s+Number(p.total||0),0);
  const cashTotal=allPurchases.filter(p=>['cash','cash_register'].includes(p.paymentSource)).reduce((s,p)=>s+Number(p.total||0),0);
  const externalTotal=allPurchases.filter(p=>!['cash','cash_register'].includes(p.paymentSource)).reduce((s,p)=>s+Number(p.total||0),0);
  return `<div class="module-summary"><div><small>Compras registradas</small><strong>${allPurchases.length}</strong></div><div><small>Total acumulado</small><strong>${money(total)}</strong></div><div><small>Pagado desde caja</small><strong>${money(cashTotal)}</strong></div><div><small>Dinero externo</small><strong>${money(externalTotal)}</strong></div><button id="newPurchaseBtn" class="primary-action">＋ Registrar compra</button></div><div class="purchase-list">${list||'<div class="empty-state">Todavía no hay compras registradas.</div>'}</div>`;
}

function openIngredientDialog(item=null) {
  $('ingredientDialogTitle').textContent=item?'Editar insumo':'Nuevo insumo'; $('ingredientId').value=item?.id||''; $('ingredientName').value=item?.name||''; $('ingredientBaseUnit').value=item?.baseUnit||'kg'; $('ingredientPurchaseUnit').value=item?.purchaseUnit||''; $('ingredientConversion').value=Number(item?.conversionFactor||1); $('ingredientMinimum').value=Number(item?.minimumStock||0); $('ingredientStock').value=Number(item?.theoreticalQuantity||0); $('ingredientCost').value=Number(item?.averageCost||0); $('ingredientActive').checked=item?.active!==false; $('ingredientDialog').showModal();
}

async function saveIngredient(event) {
  event.preventDefault(); const id=$('ingredientId').value||uid(); const existing=await getRecord('inventoryIngredients',id); const row={...(existing||{}),id,inventoryItemId:existing?.inventoryItemId||uid(),name:$('ingredientName').value.trim(),baseUnit:$('ingredientBaseUnit').value,purchaseUnit:$('ingredientPurchaseUnit').value.trim()||$('ingredientBaseUnit').value,conversionFactor:Number($('ingredientConversion').value||1),minimumStock:Number($('ingredientMinimum').value||0),theoreticalQuantity:Number($('ingredientStock').value||0),physicalQuantity:Number($('ingredientStock').value||0),averageCost:Number($('ingredientCost').value||0),active:$('ingredientActive').checked,createdAt:existing?.createdAt||nowIso(),updatedAt:nowIso(),appVersion:APP_VERSION};
  if(!row.name)return toast('Ingresa el nombre del insumo.'); const tx=db.transaction(['inventoryIngredients','syncQueue','auditLogs'],'readwrite'); tx.objectStore('inventoryIngredients').put(row); tx.objectStore('syncQueue').put(queueRecord('inventoryIngredients',row)); tx.objectStore('auditLogs').put({id:uid(),action:existing?'ingredient_updated':'ingredient_created',entity:'inventoryIngredients',entityId:id,details:{name:row.name,stock:row.theoreticalQuantity},createdAt:nowIso(),appVersion:APP_VERSION}); await transactionPromise(tx); $('ingredientDialog').close(); await renderModule('inventory'); await refreshStatus(); scheduleAutoBackup('actualización de inventario'); toast('Insumo guardado.');
}

async function openAdjustDialog(id) { const item=await getRecord('inventoryIngredients',id); if(!item)return; $('adjustIngredientId').value=id; $('adjustIngredientLabel').textContent=`${item.name}: ${inventoryNumber(item.theoreticalQuantity)} ${item.baseUnit}`; $('adjustMovementType').value='count'; $('adjustQuantity').value=Number(item.theoreticalQuantity||0); $('adjustDetail').value='Conteo físico'; $('inventoryAdjustDialog').showModal(); }

async function saveInventoryAdjustment(event) {
  event.preventDefault(); const item=await getRecord('inventoryIngredients',$('adjustIngredientId').value); if(!item)return toast('No se encontró el insumo.'); const type=$('adjustMovementType').value, qty=Number($('adjustQuantity').value||0), before=Number(item.theoreticalQuantity||0); let after=before, signed=0; if(type==='count'){after=qty;signed=after-before;} else if(type==='entry'){after=before+qty;signed=qty;} else {after=Math.max(0,before-qty);signed=after-before;} const movement={id:uid(),ingredientId:item.id,inventoryItemId:item.inventoryItemId,type,quantity:signed,absoluteQuantity:qty,beforeQuantity:before,afterQuantity:after,unitCost:Number(item.averageCost||0),detail:$('adjustDetail').value.trim(),createdAt:nowIso(),updatedAt:nowIso(),appVersion:APP_VERSION}; const updated={...item,theoreticalQuantity:after,physicalQuantity:type==='count'?after:item.physicalQuantity,lastCountedAt:type==='count'?nowIso():item.lastCountedAt,updatedAt:nowIso()}; const tx=db.transaction(['inventoryIngredients','inventoryMovementsLocal','syncQueue','auditLogs'],'readwrite'); tx.objectStore('inventoryIngredients').put(updated); tx.objectStore('inventoryMovementsLocal').put(movement); tx.objectStore('syncQueue').put(queueRecord('inventoryMovementsLocal',{...movement,ingredient:updated})); tx.objectStore('auditLogs').put({id:uid(),action:'inventory_adjusted',entity:'inventoryIngredients',entityId:item.id,details:{type,before,after,detail:movement.detail},createdAt:nowIso(),appVersion:APP_VERSION}); await transactionPromise(tx); $('inventoryAdjustDialog').close(); await renderModule('inventory'); await refreshStatus(); scheduleAutoBackup('ajuste de inventario'); toast('Inventario ajustado.');
}

async function openPurchaseDialog() {
  if ($('purchaseMarketItemId')) $('purchaseMarketItemId').value='';
  const items=await loadInventoryLocal(); if(!items.length)return toast('Primero crea un insumo.'); $('purchaseIngredient').innerHTML=items.map(x=>`<option value="${x.id}">${escapeHTML(x.name)}</option>`).join(''); $('purchaseQuantity').value='1'; $('purchaseTotal').value='0'; $('purchaseSupplier').value=''; $('purchaseNotes').value=''; updatePurchasePreview(); $('purchaseDialog').showModal();
}
function updatePurchasePreview(){const id=$('purchaseIngredient')?.value; if(!id)return; getRecord('inventoryIngredients',id).then(item=>{if(!item)return; const q=Number($('purchaseQuantity').value||0), converted=q*Number(item.conversionFactor||1); $('purchaseUnitLabel').innerHTML=`Unidad de compra<br><strong>${escapeHTML(item.purchaseUnit||item.baseUnit)}</strong>`; $('purchaseConversionPreview').textContent=`Ingresarán ${inventoryNumber(converted)} ${item.baseUnit} al inventario.`;});}

async function savePurchase(event) {
  event.preventDefault(); const ingredient=await getRecord('inventoryIngredients',$('purchaseIngredient').value); if(!ingredient)return toast('Selecciona un insumo.'); const purchaseQty=Number($('purchaseQuantity').value||0), total=Number($('purchaseTotal').value||0), converted=purchaseQty*Number(ingredient.conversionFactor||1); if(purchaseQty<=0||total<0)return toast('Revisa cantidad y precio.'); const purchase={id:uid(),purchaseItemId:uid(),ingredientId:ingredient.id,inventoryItemId:ingredient.inventoryItemId,ingredientName:ingredient.name,description:ingredient.name,purchaseUnit:ingredient.purchaseUnit,quantity:purchaseQty,convertedQuantity:converted,baseUnit:ingredient.baseUnit,total,supplier:$('purchaseSupplier').value.trim(),paymentSource:$('purchasePaymentSource').value,notes:$('purchaseNotes').value.trim(),createdAt:nowIso(),updatedAt:nowIso(),appVersion:APP_VERSION}; const before=Number(ingredient.theoreticalQuantity||0), after=before+converted, unitCost=converted>0?total/converted:0; const updated={...ingredient,theoreticalQuantity:after,averageCost:before+converted>0?((before*Number(ingredient.averageCost||0))+total)/(before+converted):unitCost,updatedAt:nowIso()}; const movement={id:uid(),ingredientId:ingredient.id,inventoryItemId:ingredient.inventoryItemId,type:'purchase',quantity:converted,beforeQuantity:before,afterQuantity:after,unitCost,detail:`Compra: ${purchaseQty} ${ingredient.purchaseUnit}`,createdAt:nowIso(),updatedAt:nowIso(),appVersion:APP_VERSION}; const tx=db.transaction(['inventoryIngredients','inventoryMovementsLocal','purchasesLocal','syncQueue','auditLogs'],'readwrite'); tx.objectStore('inventoryIngredients').put(updated); tx.objectStore('inventoryMovementsLocal').put(movement); tx.objectStore('purchasesLocal').put(purchase); tx.objectStore('syncQueue').put(queueRecord('purchasesLocal',{...purchase,ingredient:updated,movement})); tx.objectStore('auditLogs').put({id:uid(),action:'purchase_created',entity:'purchasesLocal',entityId:purchase.id,details:{ingredient:ingredient.name,total,converted},createdAt:nowIso(),appVersion:APP_VERSION}); await transactionPromise(tx); const linkedMarketItemId=$('purchaseMarketItemId')?.value; if(linkedMarketItemId && typeof markMarketItemPurchased==='function') await markMarketItemPurchased(linkedMarketItemId,purchase); $('purchaseDialog').close(); await renderModule(currentModuleKey==='purchases'?'purchases':currentModuleKey==='market'?'market':'inventory'); await refreshStatus(); scheduleAutoBackup('registro de compra'); toast('Compra registrada y stock actualizado.');
}

async function seedInitialIngredients() {
  const existing=await loadInventoryLocal(); if(existing.length&&!confirm('Ya existen insumos. ¿Agregar solamente los faltantes de la base inicial?'))return; const defaults=[['Papa','kg','arroba',11.5,10],['Pollo','presa','pollo entero',8,12],['Arroz','kg','quintal',46,8],['Carne molida hamburguesa','kg','kg',1,2],['Carne picada salchicarne','kg','kg',1,2],['Bife para lomo','unidad','kg',1,5],['Salchicha','unidad','paquete',20,15],['Pan de hamburguesa','unidad','bolsa',12,12],['Queso mozzarella','unidad','paquete',20,10],['Huevo','unidad','maple',30,12],['Aceite','litro','bidón',5,3],['Ensalada preparada','porción','lote',20,5],['Envase para llevar','unidad','paquete',50,15],['Servilleta','unidad','paquete',100,30]]; const names=new Set(existing.map(x=>x.name.toLowerCase())); const tx=db.transaction(['inventoryIngredients','syncQueue'],'readwrite'); for(const [name,base,purchase,conv,min] of defaults){if(names.has(name.toLowerCase()))continue; const row={id:uid(),inventoryItemId:uid(),name,baseUnit:base,purchaseUnit:purchase,conversionFactor:conv,minimumStock:min,theoreticalQuantity:0,physicalQuantity:0,averageCost:0,active:true,createdAt:nowIso(),updatedAt:nowIso(),appVersion:APP_VERSION}; tx.objectStore('inventoryIngredients').put(row); tx.objectStore('syncQueue').put(queueRecord('inventoryIngredients',row));} await transactionPromise(tx); await renderModule('inventory'); await refreshStatus(); toast('Base inicial de insumos cargada.');
}

renderModule = async function(key) {
  if(!['inventory','purchases'].includes(key)) return originalRenderModuleV05(key);
  const module=modules.find(item=>item[0]===key); $('salesView').classList.remove('active'); $('moduleView').classList.add('active'); const body=key==='inventory'?await renderInventoryModule():await renderPurchasesModule(); $('moduleContent').innerHTML=`<div class="module-hero"><p class="eyebrow" style="color:#ffd54d">Good King V0.8.0</p><h1>${escapeHTML(module[2])}</h1><p>${escapeHTML(module[3])}</p></div>${body}`;
  $('newIngredientBtn')?.addEventListener('click',()=>openIngredientDialog()); $('seedIngredientsBtn')?.addEventListener('click',seedInitialIngredients); $('quickPurchaseBtn')?.addEventListener('click',openPurchaseDialog); $('newPurchaseBtn')?.addEventListener('click',openPurchaseDialog); $('moduleContent').querySelectorAll('.edit-ingredient').forEach(b=>b.onclick=async()=>openIngredientDialog(await getRecord('inventoryIngredients',b.dataset.id))); $('moduleContent').querySelectorAll('.adjust-inventory').forEach(b=>b.onclick=()=>openAdjustDialog(b.dataset.id));
};

pushQueueItem = async function(item,deviceId) {
  const client=supabaseClient,businessId=authContext.businessId,userId=authContext.userId,p=item.payload;
  if(item.entity==='inventoryIngredients'){const ingredient={id:p.id,business_id:businessId,name:p.name,base_unit:p.baseUnit,purchase_unit:p.purchaseUnit||null,conversion_factor:Number(p.conversionFactor||1),average_cost:Number(p.averageCost||0),minimum_stock:Number(p.minimumStock||0),active:p.active!==false,payload:{local_version:p.appVersion||APP_VERSION},created_by:userId,created_at:p.createdAt||nowIso(),updated_at:p.updatedAt||nowIso()}; let {error}=await client.from('ingredients').upsert(ingredient,{onConflict:'id'});if(error)throw error; ({error}=await client.from('inventory_items').upsert({id:p.inventoryItemId,business_id:businessId,ingredient_id:p.id,theoretical_quantity:Number(p.theoreticalQuantity||0),physical_quantity:p.physicalQuantity==null?null:Number(p.physicalQuantity),last_counted_at:p.lastCountedAt||null,updated_by:userId,updated_at:p.updatedAt||nowIso()},{onConflict:'id'}));if(error)throw error; return;}
  if(item.entity==='inventoryMovementsLocal'){const ing=p.ingredient; let {error}=await client.from('ingredients').upsert({id:ing.id,business_id:businessId,name:ing.name,base_unit:ing.baseUnit,purchase_unit:ing.purchaseUnit||null,conversion_factor:Number(ing.conversionFactor||1),average_cost:Number(ing.averageCost||0),minimum_stock:Number(ing.minimumStock||0),active:ing.active!==false,payload:{},created_by:userId,created_at:ing.createdAt||nowIso(),updated_at:ing.updatedAt||nowIso()},{onConflict:'id'});if(error)throw error; ({error}=await client.from('inventory_items').upsert({id:ing.inventoryItemId,business_id:businessId,ingredient_id:ing.id,theoretical_quantity:Number(ing.theoreticalQuantity||0),physical_quantity:ing.physicalQuantity==null?null:Number(ing.physicalQuantity),last_counted_at:ing.lastCountedAt||null,updated_by:userId,updated_at:ing.updatedAt||nowIso()},{onConflict:'id'}));if(error)throw error; const mt=p.type==='entry'?'adjustment_in':p.type==='count'?(Number(p.quantity)>=0?'adjustment_in':'adjustment_out'):p.type==='waste'?'waste':'adjustment_out'; ({error}=await client.from('inventory_movements').upsert({id:p.id,business_id:businessId,inventory_item_id:p.inventoryItemId,movement_type:mt,quantity:Number(p.quantity),unit_cost:Number(p.unitCost||0),reference_type:'manual_adjustment',detail:p.detail||null,created_by:userId,device_id:deviceId,created_at:p.createdAt||nowIso(),updated_at:p.updatedAt||nowIso()},{onConflict:'id'}));if(error)throw error; return;}
  if(item.entity==='purchasesLocal'){const ing=p.ingredient,m=p.movement; let {error}=await client.from('ingredients').upsert({id:ing.id,business_id:businessId,name:ing.name,base_unit:ing.baseUnit,purchase_unit:ing.purchaseUnit||null,conversion_factor:Number(ing.conversionFactor||1),average_cost:Number(ing.averageCost||0),minimum_stock:Number(ing.minimumStock||0),active:true,payload:{},created_by:userId,created_at:ing.createdAt||nowIso(),updated_at:ing.updatedAt||nowIso()},{onConflict:'id'});if(error)throw error; ({error}=await client.from('inventory_items').upsert({id:ing.inventoryItemId,business_id:businessId,ingredient_id:ing.id,theoretical_quantity:Number(ing.theoreticalQuantity||0),physical_quantity:ing.physicalQuantity==null?null:Number(ing.physicalQuantity),updated_by:userId,updated_at:ing.updatedAt||nowIso()},{onConflict:'id'}));if(error)throw error; ({error}=await client.from('purchases').upsert({id:p.id,business_id:businessId,purchase_date:String(p.createdAt).slice(0,10),supplier:p.supplier||null,payment_source:p.paymentSource||'external',total:Number(p.total||0),notes:p.notes||null,created_by:userId,device_id:deviceId,created_at:p.createdAt||nowIso(),updated_at:p.updatedAt||nowIso()},{onConflict:'id'}));if(error)throw error; const pi={id:p.purchaseItemId||uid(),business_id:businessId,purchase_id:p.id,ingredient_id:p.ingredientId,description:p.ingredientName,purchase_unit:p.purchaseUnit,quantity:Number(p.quantity),converted_quantity:Number(p.convertedQuantity),unit_price:Number(p.quantity)>0?Number(p.total)/Number(p.quantity):0,line_total:Number(p.total),created_at:p.createdAt||nowIso(),updated_at:p.updatedAt||nowIso()}; ({error}=await client.from('purchase_items').upsert(pi,{onConflict:'id'}));if(error&&!String(error.message).includes('duplicate'))throw error; ({error}=await client.from('inventory_movements').upsert({id:m.id,business_id:businessId,inventory_item_id:m.inventoryItemId,movement_type:'purchase',quantity:Number(m.quantity),unit_cost:Number(m.unitCost||0),reference_type:'purchase',reference_id:p.id,detail:m.detail,created_by:userId,device_id:deviceId,created_at:m.createdAt||nowIso(),updated_at:m.updatedAt||nowIso()},{onConflict:'id'}));if(error)throw error; return;}
  if(item.entity==='productCatalog'){let payload=await ensureProductRemoteId(p);item.payload=payload;const categories=await getRemoteCategoryMap();const row={id:payload.remoteId,business_id:businessId,category_id:categories[categoryCode(payload.category)]||null,name:payload.name,description:payload.desc||null,price:Number(payload.price||0),image_url:payload.imageUrl||null,icon:payload.emoji||null,availability:payload.status==='soldout'?'sold_out':payload.status==='low'?'low_stock':'available',sort_order:Number(payload.sortOrder||0),active:payload.active!==false,payload:{local_id:payload.id,badge:payload.badge||'',image_path:payload.imagePath||''},created_by:userId,device_id:deviceId,created_at:payload.createdAt||nowIso(),updated_at:payload.updatedAt||nowIso()};const {error}=await client.from('products').upsert(row,{onConflict:'id'});if(error)throw error;return;}
  return originalPushQueueItemV05(item,deviceId);
};

pullRemoteCoreData = async function() {
  const result=await originalPullRemoteCoreDataV05(); if(!supabaseClient||!authContext||!navigator.onLine)return result; const [{data:ings,error:e1},{data:stocks,error:e2},{data:remoteProducts,error:e3}]=await Promise.all([supabaseClient.from('ingredients').select('*').eq('business_id',authContext.businessId).is('deleted_at',null),supabaseClient.from('inventory_items').select('*').eq('business_id',authContext.businessId).is('deleted_at',null),supabaseClient.from('products').select('*,product_categories(code,name)').eq('business_id',authContext.businessId)]); if(e1||e2||e3)throw(e1||e2||e3); const stockMap=Object.fromEntries((stocks||[]).map(s=>[s.ingredient_id,s])); for(const r of ings||[]){const s=stockMap[r.id]||{};await putRecord('inventoryIngredients',{id:r.id,inventoryItemId:s.id||uid(),name:r.name,baseUnit:r.base_unit,purchaseUnit:r.purchase_unit||r.base_unit,conversionFactor:Number(r.conversion_factor||1),averageCost:Number(r.average_cost||0),minimumStock:Number(r.minimum_stock||0),theoreticalQuantity:Number(s.theoretical_quantity||0),physicalQuantity:s.physical_quantity==null?null:Number(s.physical_quantity),lastCountedAt:s.last_counted_at,active:r.active!==false,createdAt:r.created_at,updatedAt:r.updated_at,appVersion:APP_VERSION,remote:true});result.pulled=(result.pulled||0)+1;} for(const row of remoteProducts||[]){const localId=row.payload?.local_id||`remote-${row.id}`;const current=await getRecord('productCatalog',localId);if(current){await putRecord('productCatalog',{...current,imageUrl:row.image_url||current.imageUrl||'',imagePath:row.payload?.image_path||current.imagePath||'',updatedAt:row.updated_at});}} await ensureDefaultCatalog();renderProducts();return result;
};

function bindV06Dialogs(){
  $('productImageFile')?.addEventListener('change',e=>{pendingProductImageFile=e.target.files?.[0]||null;removeExistingProductImage=false;updateProductImagePreview(products.find(p=>p.id===$('productId').value));}); $('removeProductImage')?.addEventListener('click',()=>{pendingProductImageFile=null;removeExistingProductImage=true;$('productImageFile').value='';updateProductImagePreview();}); $('ingredientForm')?.addEventListener('submit',saveIngredient); $('dismissIngredient').onclick=$('cancelIngredient').onclick=()=>$('ingredientDialog').close(); $('inventoryAdjustForm')?.addEventListener('submit',saveInventoryAdjustment); $('dismissInventoryAdjust').onclick=$('cancelInventoryAdjust').onclick=()=>$('inventoryAdjustDialog').close(); $('purchaseForm')?.addEventListener('submit',savePurchase); $('dismissPurchase').onclick=$('cancelPurchase').onclick=()=>$('purchaseDialog').close(); $('purchaseIngredient')?.addEventListener('change',updatePurchasePreview); $('purchaseQuantity')?.addEventListener('input',updatePurchasePreview); $('adjustMovementType')?.addEventListener('change',()=>{$('adjustQuantityLabel').firstChild.textContent=$('adjustMovementType').value==='count'?'Cantidad física contada':'Cantidad';});
}

window.addEventListener('DOMContentLoaded',()=>setTimeout(bindV06Dialogs,0));
