'use strict';
/* Good King V0.9.3 · catálogo visual y pedido móvil optimizado */
const V093_VERSION='0.9.3';
const BUILTIN_PRODUCT_PHOTOS_V093={
'coca-mini':'https://www.coca-cola.com/content/dam/onexp/bo/es/brands/coca-cola/new/coca_cola_300ml.jpg',
'coca-pop':'https://www.coca-cola.com/content/dam/onexp/bo/es/brands/coca-cola/new/coca_cola_600ml.png',
'coca-2l':'https://www.coca-cola.com/content/dam/onexp/bo/es/brands/coca-cola/new/coca_cola_2l.jpg',
'coca-3l':'https://www.coca-cola.com/content/dam/onexp/bo/es/brands/coca-cola/new/coca_cola_3l.jpg',
'jugo':'https://www.jugosbolivianos.com.bo/wp-content/uploads/2023/10/Popular-durazno-700x700.jpg',
'extra-arroz':'https://images.pexels.com/photos/8923092/pexels-photo-8923092.jpeg?auto=compress&dpr=1&h=750&w=1260',
'extra-papa':'https://images.pexels.com/photos/3727186/pexels-photo-3727186.jpeg?auto=compress&dpr=1&h=750&w=1260',
'extra-salchi':'https://images.pexels.com/photos/14018214/pexels-photo-14018214.png?auto=compress&dpr=1&h=750&w=1260',
'extra-ensalada':'https://images.pexels.com/photos/4887993/pexels-photo-4887993.jpeg?auto=compress&dpr=1&h=750&w=1260',
'extra-huevo':'https://images.pexels.com/photos/32972557/pexels-photo-32972557.jpeg?auto=compress&dpr=1&h=750&w=1260'};
function normalizeProductNameV093(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function builtinPhotoForProductV093(p){if(!p)return'';if(BUILTIN_PRODUCT_PHOTOS_V093[p.id])return BUILTIN_PRODUCT_PHOTOS_V093[p.id];const n=normalizeProductNameV093(p.name);if(n.includes('coca')&&(n.includes('mini')||n.includes('300')))return BUILTIN_PRODUCT_PHOTOS_V093['coca-mini'];if(n.includes('coca')&&(n.includes('popular')||n.includes('500')||n.includes('600')))return BUILTIN_PRODUCT_PHOTOS_V093['coca-pop'];if(n.includes('coca')&&n.includes('2')&&n.includes('lit'))return BUILTIN_PRODUCT_PHOTOS_V093['coca-2l'];if(n.includes('coca')&&n.includes('3')&&n.includes('lit'))return BUILTIN_PRODUCT_PHOTOS_V093['coca-3l'];if(n.includes('tropi')||n.includes('jugo embotellado'))return BUILTIN_PRODUCT_PHOTOS_V093['jugo'];if(n.includes('porcion')&&n.includes('arroz'))return BUILTIN_PRODUCT_PHOTOS_V093['extra-arroz'];if(n.includes('porcion')&&(n.includes('papa')||n.includes('frita')))return BUILTIN_PRODUCT_PHOTOS_V093['extra-papa'];if(n.includes('porcion')&&n.includes('salchi'))return BUILTIN_PRODUCT_PHOTOS_V093['extra-salchi'];if(n.includes('porcion')&&n.includes('ensalada'))return BUILTIN_PRODUCT_PHOTOS_V093['extra-ensalada'];if(n.includes('huevo'))return BUILTIN_PRODUCT_PHOTOS_V093['extra-huevo'];return''}
productVisualHTML=function(product,admin=false){const src=product?.imageUrl||builtinPhotoForProductV093(product),emoji=escapeHTML(product?.emoji||'🍽️');if(!src)return`<span class="food-emoji">${emoji}</span>`;const cls=admin?'admin-product-photo':'product-photo',fb=admin?'admin-fallback image-fallback-v093':'food-emoji image-fallback-v093';return`<img class="${cls}" src="${escapeHTML(src)}" alt="${escapeHTML(product?.name||'Producto')}" loading="lazy" referrerpolicy="no-referrer" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="${fb}" hidden>${emoji}</span>`};
function refreshSegmentA11yV093(id){const g=$(id);if(!g)return;g.querySelectorAll('button').forEach(b=>{const a=b.classList.contains('active');b.setAttribute('aria-pressed',a?'true':'false');b.setAttribute('aria-checked',a?'true':'false')})}
const originalSetupSegmentV093=setupSegment;setupSegment=function(id,setter){originalSetupSegmentV093(id,v=>{setter(v);refreshSegmentA11yV093(id)});refreshSegmentA11yV093(id)};
const cssV093=`.segmented button{position:relative;display:flex;align-items:center;justify-content:center;gap:7px;min-height:48px;transition:.16s;color:#211f26}.segmented button.active{background:linear-gradient(135deg,#a80710,#d9131d 64%,#ef3824)!important;color:#fff!important;box-shadow:0 7px 18px rgba(197,17,28,.30)!important}.segmented button.active:before{content:'✓';display:grid;place-items:center;width:22px;height:22px;border-radius:50%;background:#fff;color:#c9101a;font-size:14px;font-weight:1000}.segmented button[aria-pressed=false]{background:transparent;color:#211f26}.image-fallback-v093[hidden]{display:none!important}@media(max-width:760px){.cart-panel{height:min(92dvh,780px);padding:8px 16px max(12px,env(safe-area-inset-bottom))}.cart-grabber{margin:1px auto 5px}.cart-head{padding-bottom:7px}.cart-head span{font-size:12px}.cart-head strong{font-size:25px;line-height:1.05}.round-close{width:40px;height:40px;font-size:24px}.cart-items{min-height:0;max-height:min(17dvh,132px);padding:4px 0;flex:0 1 auto;overscroll-behavior:contain}.cart-line{padding:8px 0;min-height:56px}.cart-line strong{font-size:15px;line-height:1.18}.cart-line small{font-size:12px}.qty{gap:7px}.qty button{width:36px;height:36px;border-radius:12px;font-size:21px}.order-form{flex:1 1 auto;min-height:0;overflow:auto;padding-right:2px;overscroll-behavior:contain}.field-group{padding:7px 0}.field-title{margin-bottom:6px;font-size:15px}.segmented{gap:5px;padding:4px;border-radius:15px}.segmented button{min-height:44px;padding:9px 6px;font-size:15px;border-radius:12px}.segmented button.active:before{width:20px;height:20px;font-size:13px}.quick-notes{gap:5px}.quick-notes button{padding:6px 9px;font-size:11.5px}.text-note{margin-top:7px;gap:4px}.text-note input{padding:10px 12px;min-height:42px}.cart-footer{flex:0 0 auto;margin-top:4px;padding-top:8px;background:#fff}.total-row{margin-bottom:8px;font-size:17px}.total-row strong{font-size:27px}.cart-footer .primary-action{padding:12px 18px;font-size:16px}}@media(max-width:390px){.cart-panel{height:min(94dvh,790px);padding-left:13px;padding-right:13px}.cart-items{max-height:min(15dvh,112px)}.cart-line{padding:6px 0;min-height:52px}.quick-notes button{padding:5px 8px;font-size:11px}.segmented button{font-size:14px;min-height:42px}}`;
function installCssV093(){if(document.getElementById('goodKingV093Css'))return;const s=document.createElement('style');s.id='goodKingV093Css';s.textContent=cssV093;document.head.appendChild(s)}
window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{installCssV093();document.title='Good King V0.9.3';const side=document.querySelector('.side-footer span');if(side)side.textContent='V0.9.3 · Catálogo visual y pedido optimizado';refreshSegmentA11yV093('orderTypeGroup');refreshSegmentA11yV093('paymentGroup');renderProducts()},110));
/* Cargador transitorio V0.9.4: permite actualización segura sin reescribir index.html. */
(()=>{if(!document.querySelector('link[data-goodking-v094]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./v094.css?v=0.9.4';l.dataset.goodkingV094='1';document.head.appendChild(l)}if(!document.querySelector('script[data-goodking-v094]')){const s=document.createElement('script');s.src='./v094.js?v=0.9.4';s.dataset.goodkingV094='1';document.head.appendChild(s)}})();
