const fs=require('fs');
const path=require('path');
const Core=require('../js/v8-financial-core.js');
const rows=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/imports/gabriela-espinoza-mi-negocio.json'),'utf8')).map(r=>Core.normalizeHistoricalRow(r,{clientId:'gabriela',clientName:'Gabriela Espinoza'}));
const client={id:'gabriela',name:'Gabriela Espinoza'};
const account=Core.aggregateClient(client,rows,[],[]);
function assert(ok,msg){if(!ok)throw new Error(msg)}
assert(rows.length===7,'Deben existir 7 operaciones');
assert(account.pendingCount===7,'Deben existir 7 deudas activas');
assert(Math.abs(account.totalBought-7521.20)<0.001,`Total comprado incorrecto ${account.totalBought}`);
assert(Math.abs(account.totalPaid-2095.00)<0.001,`Pagado incorrecto ${account.totalPaid}`);
assert(Math.abs(account.totalDebt-5426.20)<0.001,`Saldo incorrecto ${account.totalDebt}`);
assert(rows.every(r=>r.inventoryImpact===false),'Las históricas no deben afectar inventario');
assert(rows.every(r=>r.origin==='Importado desde Mi Negocio'),'Origen incorrecto');
const allocation=Core.allocatePayment(rows,[],500,'oldest',[]);
assert(allocation.allocations.length===2,'Pago de 500 debe alcanzar dos deudas');
assert(Math.abs(allocation.allocations[0].amount-243.20)<0.001,'Primera asignación incorrecta');
assert(Math.abs(allocation.allocations[1].amount-256.80)<0.001,'Segunda asignación incorrecta');
const payment={id:'p1',amount:500,status:'posted',allocations:allocation.allocations};
const after=Core.aggregateClient(client,rows,[payment],[]);
assert(Math.abs(after.totalDebt-4926.20)<0.001,'El pago parcial no redujo el saldo');
const voided={...payment,status:'voided'};
const restored=Core.aggregateClient(client,rows,[voided],[]);
assert(Math.abs(restored.totalDebt-5426.20)<0.001,'La anulación no restauró el saldo');
console.log('OK V8.2.9 Gabriela:',{operations:rows.length,paid:account.totalPaid,balance:account.totalDebt,afterPayment:after.totalDebt,restored:restored.totalDebt});
